name: Generate and Deploy LDoc

on:
  push:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - uses: actions/checkout@v3

      # 2. Cache LuaRocks state to speed up repeated builds
      - name: Cache LuaRocks
        uses: actions/cache@v4
        with:
          path: ~/.luarocks
          key: ${{ runner.os }}-luarocks
          restore-keys: |
            ${{ runner.os }}-luarocks

      # 3. Install Lua and LuaRocks
      - name: Install Lua and LuaRocks
        run: |
          sudo apt-get update
          sudo apt-get install -y lua5.4 luarocks

      # 4. Install LDoc locally
      - name: Install LDoc
        run: luarocks install ldoc --local
          
      # 5. Build docs
      - name: Build LDoc
        run: eval "$(luarocks path --bin)" && ldoc .

      # 5. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc
